# Custom Language File for Launcher Customizer

[ejs.app]
title = "PixeLand Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/koopave/ElectronLauncher"
mediaTwitterURL = "https://twitter.com/koopave"
mediaInstagramURL = "https://instagram.com/koopave"
mediaYouTubeURL = "https://youtube.com/@koopave"
mediaDiscordURL = "https://discord.gg/JFeqmX8Y3J"

[ejs.settings]
sourceGithubLink = "https://github.com/koopave/ElectronLauncher"
supportLink = "https://github.com/koopave/ElectronLauncher/pulls"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR PIXELAND"
welcomeDescription = "Nous espérons que vous vivrez une aventure incroyable et amusante sur nos serveurs. "
welcomeDescCTA = "Prêt(e) à nous rejoindre ?"
